%YAML:1.0
---
# dataset
dataset.path: ../dataset/

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.ux: 325.1
camera.vy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50

